### ISSUE TITLE
More Planning issue potentially

### ISSUE THREAD

**Issue by Trisscar05** [DingoDjango/HandMeThatBrickLite#3]
On load of save file, clicking on any of the More Planning options for the first time produces this in the console:
Called MaterialsNeeded on a Blueprint_Install.
Verse.Log:Error(String, Boolean)
RimWorld.Blueprint_Install:MaterialsNeeded()
HMTBLite.HarmonyPatches:Patch_Postfix_WorkGivers_Job(WorkGiver_ConstructDeliverResources, Thing, Job&)
RimWorld.WorkGiver_ConstructDeliverResourcesToBlueprints:JobOnThing_Patch1(Object, Pawn, Thing, Boolean)
RimWorld.WorkGiver_Scanner:HasJobOnThing(Pawn, Thing, Boolean)
RimWorld.<TryIssueJobPackage>cAnonStorey1:<>m0(Thing)
Verse.<ClosestThingReachable>cAnonStorey0:<>m0(Thing)
Verse.GenClosest:ClosestThing_Global(IntVec3, IEnumerable, Single, Predicate1, Func2)
Verse.GenClosest:ClosestThingReachable(IntVec3, Map, ThingRequest, PathEndMode, TraverseParms, Single, Predicate1, IEnumerable1, Int32, Int32, Boolean, RegionType, Boolean)
ExpandedRoofing.ClosestThingReachableHelper:ClosestThingReachableWrapper(IntVec3, Map, ThingRequest, PathEndMode, TraverseParms, Single, Predicate1, IEnumerable1, Int32, Int32, Boolean, RegionType, Boolean)
RimWorld.JobGiver_Work:TryIssueJobPackage_Patch0(Object, Pawn, JobIssueParams)
Verse.AI.ThinkNode_PrioritySorter:TryIssueJobPackage(Pawn, JobIssueParams)
Verse.AI.ThinkNode_Priority:TryIssueJobPackage(Pawn, JobIssueParams)
Verse.AI.ThinkNode_Tagger:TryIssueJobPackage(Pawn, JobIssueParams)
Verse.AI.ThinkNode_Subtree:TryIssueJobPackage(Pawn, JobIssueParams)
Verse.AI.ThinkNode_Priority:TryIssueJobPackage(Pawn, JobIssueParams)
Verse.AI.ThinkNode_Conditional:TryIssueJobPackage(Pawn, JobIssueParams)
Verse.AI.ThinkNode_Priority:TryIssueJobPackage(Pawn, JobIssueParams)
Verse.AI.Pawn_JobTracker:DetermineNextJob_Patch1(Object, ThinkTreeDef&)
Verse.AI.Pawn_JobTracker:TryFindAndStartJob()
Verse.AI.Pawn_JobTracker:EndCurrentJob(JobCondition, Boolean)
Verse.AI.Pawn_JobTracker:JobTrackerTick()
Verse.Pawn:Tick_Patch1(Object)
Verse.TickList:Tick()
Verse.TickManager:DoSingleTick()
Verse.TickManager:TickManagerUpdate()
Verse.Game:UpdatePlay()
Verse.Root_Play:Update()

Hugslog in case that happens to help any:
https://git.io/fh10W

**Comment by DingoDjango** [comment]
This mod is no longer supported/necessary in the current version of RW.
